apiVersion: apps/v1
kind: Deployment
metadata:
  name: hostservice-deploy
spec:
  selector:
    matchLabels:
      app: hostservice
  template: # => 여기부터 pod템플릿
    metadata:
      labels:
        app: hostservice
    spec:
      containers:
      - name: hostservice-container
        image: kajh7570/node-app:6675a009824fe63d585b56954be1452c912aabbe
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
