apiVersion: apps/v1
kind: Deployment
metadata:
  name: hostservice-deploy
spec:
  selector:
    matchLabels:
      app: hostservice
  template: # => 여기부터 pod템플릿
    metadata:
      labels:
        app: hostservice
    spec:
      containers:
      - name: hostservice-container
        image: kajh7570/hostservice:6808c585cef87c68af26ec5748306baf1fb1804b
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
