apiVersion: apps/v1
kind: Deployment
metadata:
  name: hostservice-deploy
spec:
  selector:
    matchLabels:
      app: hostservice
  template: # => 여기부터 pod템플릿
    metadata:
      labels:
        app: hostservice
    spec:
      containers:
      - name: hostservice-container
        images: kajh7570/node-app:74ce07f9cf6ccaa23426dbfcca75056b8f76da97
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
